version: "3.9"

services:
  user-service:
    build: 
      context: .
    image: jelou-user-service-image:latest
    container_name: jelou-user-service
    ports:
      - "8086:3000"         # host:contenedor
    depends_on:
      - postgres
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SSL=${DB_SSL}
  postgres:
    image: docker.io/library/postgres:14
    container_name: postgres_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  pgAdmin:
    image: docker.io/dpage/pgadmin4:9.6.0
    container_name: pgadmin4
    depends_on:
      - postgres
    ports:
      - "8085:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}

volumes:
  postgres_data:



